### ISSUE TITLE
How to register the vue-snotify?

### ISSUE THREAD

**Issue by hoandang** [artemsky/vue-snotify#1]
Hi, I got this error message and can't figure out how to register the component. It is not in the example.
`Unknown custom element: <vue-snotify> - did you register the component correctly? For recursive components, make sure to provide the "name" option`

**Comment by artemsky** [comment]
Hi! Did you look the [Documentation - Install section](https://github.com/artemsky/vue-snotify/blob/master/documentation/v1/install.md)?

**Comment by hoandang** [comment]
Hi, I did follow the instruction, but I think there is missing something about registering the `<vue-snotify></vue-snotify>` component. Does it suppose to be register something like:

    import VueSnotify from 'vue-snotify'
    export default 
    {
        components: {VueSnotify}
    }

Or the component automatically registers itself when I `import {SnotifyService} from 'vue-snotify'`

Here is my current structure

### app.js

    Vue.use(require('vue-snotify'));
    Vue.component('blocks', require('./components/Blocks.vue'));

    new Vue({
        el: '#app'
    });

### Blocks.vue
    <template>
    <div>
        <h1>Blocks component</h1>
        <vue-snotify></vue-snotify>
     </div>
    </template>

    <script>
    import {SnotifyService} from 'vue-snotify';
    export default { }
    </script>

**Comment by artemsky** [comment]
you shouldn't use `require('vue-snotify')`.
Because of `vue-snotify` does not export default member.

You should use it like this.
```javascript
import {Snotify} from 'vue-snotify';
Vue.use(Snotify)
```

**Comment by hoandang** [comment]
`Vue.use(require('vue-snotify').Snotify)` works for me. Thanks

**Comment by rainabba** [comment]
Please pardon me because I'm still fairly new to Vuejs, but what's with the Vue.use() calls? I can't even use the plugin because it is trying to call `window.Vue.use()` in the same way I see here, but .use() is undefined (and my app works fine along with my component and all the others I use).

What am I missing or failing to see/understand? I'm on Vue@2.5.17 and vue-snotify@3.2.1
