### ISSUE TITLE
integrate it in HTML + JS

### ISSUE THREAD

**Issue by nos86** [artemsky/vue-snotify#13]
Hi,
I'm approaching to this amazing component of Vue, unfortunately, I'm still having an issue.

my code is:
```html
<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<div id='app'>
	<div> </div>	
</div>

	<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
	<script src='js/vue.js'></script>
	<script src='js/vue-strap.js'></script>
	<script src='js/vue-snotify.js'></script>
	<script>
	var vm = new Vue({
			el:"#app",
			data:{ },
		});
	setTimeout(function(){
		console.log("Hello World");
		vm.$snotify.simple("hello world..!");
	}, 2000);
	</script>

</body>
</html>
```

When I open this page on my browser, the script is executed without errors or warnings, vue event is raised, but nothing happens on the screen.
Here a screenshot of the result
<img width="1438" alt="schermata 2017-11-20 alle 21 50 47" src="https://user-images.githubusercontent.com/6265510/33040943-f168d6ee-ce3c-11e7-8356-d15a4acb39fc.png">

Can you help me to understand where the error is?

Thanks in advance,
Salvo

**Comment by nos86** [comment]
After several tests, I was able to solve partially the issue.
I forgot to include <vue-snotify>
But, now I'm able to see the message, but I'm not able to load the css for the correct visualization.

In your repository these css are saved like scss. I have any change to import in the html like a css or using any Vue module?

Thanks, 
Salvo

**Comment by artemsky** [comment]
#### CDN
  - JS
    - [unpkg.com](https://unpkg.com/vue-snotify@latest/vue-snotify.min.js) | [jsDelivr.com](https://cdn.jsdelivr.net/npm/vue-snotify@latest/vue-snotify.min.js)
  - CSS
    - material [unpkg.com](https://unpkg.com/vue-snotify@latest/styles/material.css) | [jsDelivr.com](https://cdn.jsdelivr.net/npm/vue-snotify@latest/styles/material.css)
    - simple [unpkg.com](https://unpkg.com/vue-snotify@latest/styles/simple.css) | [jsDelivr.com](https://cdn.jsdelivr.net/npm/vue-snotify@latest/styles/simple.css)
    - dark [unpkg.com](https://unpkg.com/vue-snotify@latest/styles/dark.css) | [jsDelivr.com](https://cdn.jsdelivr.net/npm/vue-snotify@latest/styles/dark.css)
