### ISSUE TITLE
icon not showing

### ISSUE THREAD

**Issue by JKHeadley** [artemsky/vue-snotify#15]
Great project! The notifications seem to work well, however I'm not sure if the icons are supposed to display by default or not. Do I need to set the icons manually?  I am using the material design.  Thanks!

**Comment by artemsky** [comment]
Default icons included in **styles** bundle

**Comment by JKHeadley** [comment]
Using version 3.0.1

My code looks like:

`main.js`
```javascript
import 'vue-snotify/styles/material.css'
import Snotify, { SnotifyPosition } from 'vue-snotify'

Vue.use(Snotify, {
  toast: {
    position: SnotifyPosition.rightTop
  }
})
```

and in my component:
```javascript
 this.$snotify.success('User updated', 'Success!')
```

Which results in:

![screen shot 2017-11-29 at 4 32 02 pm](https://user-images.githubusercontent.com/12631935/33406705-084efd56-d523-11e7-9964-a37c452fc6b7.png)

As you can see for some reason doesn't include an icon.

**Comment by artemsky** [comment]
Hmm....so strange.

I reproduced your code and I see icons in all stable browsers.
![image](https://user-images.githubusercontent.com/16777197/33420275-9f0ea5d2-d5b6-11e7-933a-7b27967e3d0c.png)

Pls, tell me your browser version.

**Comment by JKHeadley** [comment]
I'm using chrome Version 62.0.3202.94.

Also, the notification for your demo works on my same browser:

![screen shot 2017-11-30 at 1 04 01 am](https://user-images.githubusercontent.com/12631935/33422388-681c3540-d56a-11e7-8cca-1aac63db4c5a.png)

**Comment by JKHeadley** [comment]
Hmm, looking into this more it appears that the icon width and height were set to 0.  If I set them to 48px then the icon appears.

**Comment by artemsky** [comment]
@JKHeadley `npm i vue-snotify@latest` should fix this

**Comment by JKHeadley** [comment]
It works, thanks for the fix!
