### ISSUE TITLE
Animation issue on Firefox

### ISSUE THREAD

**Issue by orkin2913** [artemsky/vue-snotify#17]
Hi, there is a problem on Firefox with toast exit animation.
In some cases toast, near ending of its exit animation, suddenly goes back for a while and then disappears normally.
I use Firefox Quantum 57.0
![Preview](https://i.imgur.com/aNvysT0.gif)

**Comment by artemsky** [comment]
Ah, that new CSS Engine.....I'll try to fix this

**Comment by artemsky** [comment]
Still can't fix - `Second minor issue` from #18

**Comment by agm1984** [comment]
This appears to still be happening

![1551752302438](https://user-images.githubusercontent.com/17655219/54555121-4fc6b500-4973-11e9-8a19-67941a00d17e.jpg)
