### ISSUE TITLE
Next animation issues

### ISSUE THREAD

**Issue by orkin2913** [artemsky/vue-snotify#18]
Hi, it's me again 😆
Today I found next problems with animations.
Tested on Firefox 57.0 and Chrome 62.0

First major issue:
when the newOnTop option is disabled and a lot of toasts are sent with a very small interval (about 200-300ms) something strange is happening. This is probably the case when a new toast is sent when the oldest expires
![Preview1](https://i.imgur.com/YzIBtQ2.gif)
Code for reproduction

```javascript
Vue.use(Snotify, { global: { newOnTop: false } })
setInterval(() => {
  vm.$snotify.success('Example body content', 'Example Title')
}, 200)
```

Second minor issue:
when the newOnTop option is enabled there is no "dropdown" animation when the oldest toast disappears. Rest of toasts just "jumps" down
![Prewiev2](https://i.imgur.com/n82Z9un.gif)

**Comment by artemsky** [comment]
#17
