### ISSUE TITLE
Notification not showing on route change

### ISSUE THREAD

**Issue by JKHeadley** [artemsky/vue-snotify#19]
Hello! I am having an issue when trying to show a notification right before changing the route.  For example, if a user logs in, I want to show a "Login successful" notification and immediately direct the user from the "/login" route to "/" like so:

```javascript
            this.$snotify.success('Login successful', 'Success!')
            this.$router.push('/')
```

I would expect the notification to display on the next view, but it does not.  However, if I then call a separate notification while in the same view, both the new notification and the old "Login successful" notification will appear.  After experimenting with this, it appears that any time a notification is called immediately before the route is changed, the notification will be added to a queue, but will not display.  As soon as a notification is called without a route change, all of the queued notifications will display along with the new one.

**Comment by artemsky** [comment]
You should put `<vue-snotify / >` outside of your router outlet

**Comment by JKHeadley** [comment]
This is perfect, thanks!
