### ISSUE TITLE
how to use vue-snotify in vue-typescript

### ISSUE THREAD

**Issue by AmarPotki** [artemsky/vue-snotify#2]
Hi
May u help me how to use Vue-snotify in  Vue-typescript project
if u can give me a sample

**Comment by artemsky** [comment]
Thank you for your question. 
Actually, I did not try it before. I generated typings only

Now I see that there were some bugs inside this.
So I resolved them and created new github repo with typescript example

https://github.com/artemsky/vue-snotify-typescript-example

make sure yo update latest version `npm i vue-snotify@latest`

Have fun!

**Comment by AmarPotki** [comment]
Thank for reply
