### ISSUE TITLE
Async notification never dissapears

### ISSUE THREAD

**Issue by hlozancic** [artemsky/vue-snotify#20]
config.timeout is not working for async type...

resolve({title: 'Success', body: 'All ok...', config: {timeout: 3000, closeOnClick: true}})

This will not disappear after 3 seconds, but it can be closed on click

Testable even on demo: https://artemsky.github.io/vue-snotify/ (just click Async)

**Comment by Doublemedia** [comment]
I am having the same issue. Is this normal behaviour?

**Comment by justustheis** [comment]
anything new on this topic? I also have the same issue

**Comment by havryliv** [comment]
@artemsky 
Can you provide an update on the status of the current issue?

**Comment by hrabbit** [comment]
I'm also seeing this issue quite frequently. I've resorted to calling clear in some places to get around it but it certainly isn't ideal in the slightest.

On a side note, I still think this project r0x! :D

**Comment by tralmix** [comment]
I am also having this issue with Vue-Snotify v3.0.4 and Vue v2.5.16. However, looking at the [documentation ](https://artemsky.github.io/vue-snotify/documentation/api/snotify.html#async)I found that if you add a config after your promise function, the timeout starts working. `{ title:'', body:'', () => new Promise(), { timeout: 3000 } }`. While it would be nice if it functioned on the timeouts provided in the resolve/reject of the Promise, this is at least a way to get it working again.

**Comment by tralmix** [comment]
Dealing with this more the async toast appears to only respond to the timeout of the initial config and not the resolve/reject configs

**Comment by tralmix** [comment]
Look through the code and watching in debug, all the config settings are properly copied over from the resolve/reject of the passed in Promise. However, I am having trouble identifying where the controls associated with the timeout are supposed to be set. Forgive me, first time actually using typescript so it took me a bit to walk through the code. @artemsky

**Comment by justustheis** [comment]
Is there any workaround available?
