### ISSUE TITLE
Can I use vue-snotify with some.js?

### ISSUE THREAD

**Issue by ferrinweb** [artemsky/vue-snotify#31]
use like this:
`import { Snotify } from 'vue-snotify'
Snotify.success({…})`
Because there is no vue instance in abc.js file.

**Comment by bojanxmk** [comment]
Interested in this as well. +1

**Comment by artemsky** [comment]
Do you want to use this lib without vue.js?

**Comment by ferrinweb** [comment]
Use this plugin in a vue project, but not in *.vue template file, example, use it in store.js of vuex.

**Comment by artemsky** [comment]
https://github.com/artemsky/vue-snotify/issues/27
