### ISSUE TITLE
Custom toast position in px, offset, margin 

### ISSUE THREAD

**Issue by conradolk** [artemsky/vue-snotify#32]
I have a top navigation bar and the toast overlaps on top of it, i would like to set an offset/margin to the "topRight" position for example, maybe a porcentage, pixels or both.

**Comment by artemsky** [comment]
You can override toast positions as you want 
https://github.com/artemsky/vue-snotify/blob/master/src/styles/_shared/snotify.scss

and then import @import "~vue-snotify/styles/{themeName}";

**Comment by Piotr196** [comment]
@artemsky Could you please give an example how to do it? Should I write some css in style tag or something else?

OK. I managed to override it by creating css in style tag, removing "scoped" attribute.

**Comment by crackernutter** [comment]
@Piotr196 what was the CSS you created in the style tag and how did you reference it when creating the toast?  I'm also unclear on how to create position overrides this way...

**Comment by Piotr196** [comment]
@crackernutter 
I did something like
```
<style>
    .snotify-rightTop {
        margin-top: 100px;
    }
</style>
```
in App.vue but I am aware that it is not the best way :) Nonetheless, it works.
