### ISSUE TITLE
angular SnotifyModule Show template error

### ISSUE THREAD

**Issue by emailer00752** [artemsky/vue-snotify#33]
When i add SnotifyModule to the app.module.ts -> imports array [ SnotifyModule ], the page not renders and throw the error shown below to the browser console window. please guide. thanks in advance

Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngIfElse' since it isn't a known property of 'div'. ("fy-prompt *ngIf="toast.config.type === state.promptType" [toast]="toast"> </ng-snotify-prompt> <div [ERROR ->]*ngIf="!toast.config.icon; else elseBlock" [ngClass]="['snotify-icon', (toast.config.iconClass || 'sn"): ToastComponent@0:1167
Property binding ngIfElse not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("snotify-prompt *ngIf="toast.config.type === state.promptType" [toast]="toast"> </ng-snotify-prompt> [ERROR ->]<div *ngIf="!toast.config.icon; else elseBlock" [ngClass]="['snotify-icon', (toast.config.iconClass |"): ToastComponent@0:1162
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("gClass]="['snotify-icon', (toast.config.iconClass || 'snotify-icon--' + toast.config.type)]"></div> [ERROR ->]<ng-template #elseBlock> <img class="snotify-icon" [src]='toast.config.icon' /> </ng-template> </div>"): ToastComponent@0:1312
Can't bind to 'ngIfElse' since it isn't a known property of 'div'. ("[ngStyle]="{'width': (state.progress * 100) + '%'}"></span> </div> <div class="snotifyToast__inner" [ERROR ->]*ngIf="!toast.config.html; else toastHTML"> <div class="snotifyToast__title" *ngIf="toast.title">{{to"): ToastComponent@0:786
Property binding ngIfElse not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("yToast__progressBar__percentage" [ngStyle]="{'width': (state.progress * 100) + '%'}"></span> </div> [ERROR ->]<div class="snotifyToast__inner" *ngIf="!toast.config.html; else toastHTML"> <div class="snotifyToast"): ToastComponent@0:753
'ng-template' is not a known element:

**Comment by artemsky** [comment]
Pls, it's the vue.js repo
