### ISSUE TITLE
Add close button

### ISSUE THREAD

**Issue by radudalbea** [artemsky/vue-snotify#37]
Hi, could you please add a close button as an X on the top - right corner? I am using a hack right now by positioning a button absolute but when I click on it the main click event is also triggered and I run a different code for that event. You should put the main click event on a separated container and add a simple close button with his own event. I can help you with it if you want.

**Comment by paulsuceveanu** [comment]
I have the same problem. I cannot dismiss it without triggering the main click event.

**Comment by artemsky** [comment]
Will be done in next release.
