### ISSUE TITLE
Possible bug on backdrop

### ISSUE THREAD

**Issue by davidlandais** [artemsky/vue-snotify#45]
We are using your plugin in a project and need to use the `backdrop` property when displaying a `confirm` notification (using the option object). When we `remove`the toast on confirmation action, we are displaying an other notification (success, or error). The backdrop is appearing even without the backdrop property set.
So, we are trying to set backdrop: -1 to the sucess or error notification and this time, the backdrop is not visible but still present in the DOM with the css property opacity: 0. So we can't continue to navigate etc.

Is it a normal behavior ?

**Comment by davidlandais** [comment]
Yes i tried with -1. But the backdrop is not visible and still present in the DOM with the css property opacity: 0. Then the backdrop is taking all the place and is hidden. So, the navigation is not possible anymore

**Comment by mitsuakiwatanabe** [comment]
Try setting 0.1 or more, not -1.
``` javascript
this.$snotify.confirm(
  'body',
  'title',
  {
    backdrop: 0.3,
    buttons: [
        {
          text: 'yes',
          action: (toast) => {
            // some process
            this.$snotify.remove(toast.id);
            this.$snotify.success(
              'success message here',
              {
                  backdrop: 0.3 // not -1
              }
            );
          },
        },
        {
          text: 'no',
          action: (toast) => {
            this.$snotify.remove(toast.id);
            this.$snotify.warning(
              'warning message here',
              {
                  backdrop: 0.3 // not -1
              }
            );
          },
        },
    ]
  }
);
```
