### ISSUE TITLE
Async toast missing config argument

### ISSUE THREAD

**Issue by grantcarthew** [artemsky/vue-snotify#5]
Hi @artemsky,
I was just using the async toast again in a different component and found I didn't want the backdrop for this notification. I can't disable it within the async call because it doesn't have a config option.

I'm not using the action option, however even if I was using the action I may want to change the default behavior of the async notification.

I managed to get around it by setting the `this.$snotify.config.backdrop = -1` however this is not the default that I would like.

Am I missing something?

You could change the api to be something like this:

```js

async (body, title, config, action) {
  if (Object.prototype.toString.call(config.then) === '[object Function]') {
    action = config
  }
  // Process config...
}

```
By doing this users can pass in a `body, title, config, action`, or just the `body, title, action`.
You could check for the config being an being an object also if needed.

Reading through your code to ask this question I have discovered the async toast is really a simple toast. I might change to using the simple toast and set the type to async.

**Comment by artemsky** [comment]
Hi @grantcarthew
Yeah, it is the simple toast. Which have the sense to use only with action param.

I already solved this problem with my Angular version
And I decided to solve that problem in the following way
```
(body: string, action: Promise<Snotify>): SnotifyToast
(body: string, title: string, action: Promise<Snotify>): SnotifyToast
(body: string, action: Promise<Snotify>, config: SnotifyToastConfig): SnotifyToast
(body: string, title: string, action: Promise<Snotify>, config: SnotifyToastConfig): SnotifyToast
```
This weekend I planned to bring all new changes and features from Angular version to this(Vue) version

Couple of features/changes in next version
> ### Callbacks totally removed from $snotify
> Now you have jQuery-like syntax on toast object
```js
service.prompt('Accept license', {
  placeholder: 'Enter your age',
  buttons: [
    {text: 'Accept', action: (toast) => { toast.valid ? service.remove(toast.id) : false }, bold: true},
    {text: 'Cancel' }
  ]
}).on('input', (toast: Snotify) => {
  if (+toast.value >= 21) {
    toast.valid = true;
  } else {
    toast.valid = false;
  }
}).on('hidden', () => {
  /* do some stuff */
})
```

> ### Toast validation (using class names) - `toast.valid = true | false`

> ### Arguments order

Before
```js
service.simple(body)
service.simple(body, null, config)
service.async(body, null, action)
service.async(null, null, action, config)
```
Now
```js
service.simple(body)
service.simple(body, config)
service.simple(body, title)
service.simple(body, title, config)
service.async(body, action)
service.async(body, title, action)
service.async(body, action, config)
service.async(body, title, action, config)
```

> ### Buttons  
> Now button action get only one param of type SnotifyToast and by default removes toast
```
 action: (toast: SnotifyToast) => service.remove(toast.id)
```

> ### Default custom toast config on app initialization
> ### Icons and other css-like stuff totally moved from js to css code
> ## All another stuff is optimizations and should not touch you

**Comment by grantcarthew** [comment]
Sounds good mate. I'll try the simple toast today and see how it goes. Thanks, this is a great package.
